version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    volumes:
      - .:/app 
    depends_on:
      - db
      - adminer
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digicar
  db:
    image: postgres
    volumes:
      - ./docker/data-volume/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=adminer.node.localhost
      - VIRTUAL_PORT=8080

volumes:
  db-data:
